name: Build & Package Extensions

on:
  workflow_dispatch:
  push:
    paths:
      - "crates/extensions/**"

jobs:
  build:
    strategy:
      matrix:
        include:
          - target: aarch64-apple-darwin
            runner: macos-latest
            lib_ext: dylib
            platform: darwin-aarch64
          - target: x86_64-apple-darwin
            runner: macos-latest
            lib_ext: dylib
            platform: darwin-x86_64
          - target: x86_64-unknown-linux-gnu
            runner: ubuntu-latest
            lib_ext: so
            platform: linux-x86_64
          - target: x86_64-pc-windows-gnu
            runner: windows-latest
            lib_ext: dll
            platform: windows-x86_64

    runs-on: ${{ matrix.runner }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install dependencies (Ubuntu only)
        if: matrix.platform == 'linux-x86_64'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libxcb1 libxrandr2 libdbus-1-3 libx11-dev libgtk-3-dev \
            libsoup2.4-dev libwebkit2gtk-4.1-dev libappindicator3-dev \
            librsvg2-dev patchelf libdbus-1-dev pkg-config

      - name: Install dependencies (Windows only)
        if: matrix.platform == 'windows-x86_64'
        shell: pwsh
        run: choco install zip -y

      - name: Install Rust stable and add target
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: "./ -> target"

      - name: Build all extensions
        shell: bash
        run: |
          for ext in crates/extensions/*; do
            [ -d "$ext" ] || continue
            pushd "$ext"
            cargo build --release --target ${{ matrix.target }}
            popd
          done

      - name: Package each extension for ${{ matrix.platform }}
        shell: bash
        run: |
          mkdir -p dist
          for ext in crates/extensions/*; do
            [ -d "$ext" ] || continue
            name=$(basename "$ext")
            out="dist/$name/${{ matrix.platform }}"
            mkdir -p "$out"

            # select & rename library to match lib_filename
            if [[ "${{ matrix.platform }}" == "windows-x86_64" ]]; then
              src="target/${{ matrix.target }}/release/${name}.${{ matrix.lib_ext }}"
              lib_filename="lib.${{ matrix.lib_ext }}"
            else
              src="target/${{ matrix.target }}/release/lib${name}.${{ matrix.lib_ext }}"
              case "${{ matrix.platform }}" in
                darwin-*) lib_filename="lib.dylib" ;;
                linux-*) lib_filename="lib.so" ;;
              esac
            fi

            cp "$src" "$out/$lib_filename"
            cp "$ext/assets/icon.svg" "$out/"
            cp "$ext/assets/manifest.json" "$out/"

            pushd "$out"
            zip -r "${name}_${{ matrix.platform }}.zip" ./*
            popd
          done

      - name: Upload zipped artifacts
        uses: actions/upload-artifact@v4
        with:
          name: extensions-${{ matrix.platform }}
          path: dist/*/${{ matrix.platform }}/*.zip

  generate-manifests:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download all ZIP artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist

      - name: Generate each extension’s update_manifest.json
        shell: bash
        run: |
          set -euo pipefail

          # gather unique extension names from all zips
          mapfile -t names < <(
            find dist -type f -name "*.zip" \
            | xargs -n1 basename \
            | sed -E 's/^(.+)_.+\.zip$/\1/' \
            | sort -u
          )

          for name in "${names[@]}"; do
            # version lives in the source assets folder
            version=$(jq -r .version crates/extensions/"$name"/assets/manifest.json)

            # start JSON
            manifest="{\"version\":\"$version\",\"assets\":{"
            first=true

            # iterate over every zip belonging to this extension
            while IFS= read -r zip; do
              fname=$(basename "$zip")
              # extract platform (the part after the first underscore, before .zip)
              plat="${fname#${name}_}"
              plat="${plat%.zip}"
              checksum=$(sha256sum "$zip" | cut -d' ' -f1)
              url="https://my.cdn/$name/${fname}"

              if $first; then
                first=false
              else
                manifest+=","
              fi

              manifest+="\"$plat\":{\"url\":\"$url\",\"checksum\":\"$checksum\"}"
            done < <(find dist -type f -name "${name}_*.zip")

            manifest+="}}"

            # write out
            outdir="dist/$name"
            mkdir -p "$outdir"
            echo "$manifest" > "$outdir/update_manifest.json"
            echo "→ $outdir/update_manifest.json"
          done

      - name: Upload update_manifests
        uses: actions/upload-artifact@v4
        with:
          name: extension-update-manifests
          path: dist/*/update_manifest.json
