name: Build & Package Extensions

on:
  workflow_dispatch:
  push:
    paths:
      - "crates/extensions/**"

env:
  BASE_URL: "https://github.com/nwrenger/pointy/releases/latest/download"

jobs:
  build:
    strategy:
      matrix:
        include:
          - target: aarch64-apple-darwin
            runner: macos-latest
            lib_ext: dylib
            platform: darwin-aarch64
          - target: x86_64-apple-darwin
            runner: macos-latest
            lib_ext: dylib
            platform: darwin-x86_64
          - target: x86_64-unknown-linux-gnu
            runner: ubuntu-latest
            lib_ext: so
            platform: linux-x86_64
          - target: x86_64-pc-windows-gnu
            runner: windows-latest
            lib_ext: dll
            platform: windows-x86_64

    runs-on: ${{ matrix.runner }}
    env:
      TARGET: ${{ matrix.target }}
      PLATFORM: ${{ matrix.platform }}
      LIB_EXT: ${{ matrix.lib_ext }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install dependencies (Ubuntu only)
        if: matrix.platform == 'linux-x86_64'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libxcb1 libxrandr2 libdbus-1-3 libx11-dev libgtk-3-dev \
            libsoup2.4-dev libwebkit2gtk-4.1-dev libappindicator3-dev \
            librsvg2-dev patchelf libdbus-1-dev pkg-config

      - name: Install dependencies (Windows only)
        if: matrix.platform == 'windows-x86_64'
        shell: pwsh
        run: choco install zip -y

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: "./ -> target"

      - name: Build extensions
        shell: bash
        run: |
          for ext in crates/extensions/*; do
            [ -d "$ext" ] || continue
            pushd "$ext"
            cargo build --release --target "$TARGET"
            popd
          done

      - name: Prepare dist
        run: mkdir -p dist

      - name: Package extensions
        shell: bash
        run: |
          #!/usr/bin/env bash
          set -euo pipefail

          root_dir="$(pwd)"
          dist_dir="$root_dir/dist"

          for ext in crates/extensions/*; do
            [ -d "$ext" ] || continue
            name=$(basename "$ext")

            # figure out the built lib path and how to name it inside the zip
            if [[ "$PLATFORM" == "windows-x86_64" ]]; then
              src="$root_dir/target/$TARGET/release/${name}.${LIB_EXT}"
              lib_filename="lib.${LIB_EXT}"
            else
              src="$root_dir/target/$TARGET/release/lib${name}.${LIB_EXT}"
              case "$PLATFORM" in
                darwin-*) lib_filename="lib.dylib" ;;
                linux-*) lib_filename="lib.so"    ;;
              esac
            fi

            if [ ! -f "$src" ]; then
              echo "⚠️  Skipping $name for $PLATFORM — file not found: $src" >&2
              continue
            fi

            staging=$(mktemp -d)
            cp "$src" "$staging/$lib_filename"
            cp "$ext/assets/icon.svg"    "$staging/"
            cp "$ext/assets/manifest.json" "$staging/"

            pushd "$staging" > /dev/null
              zip -r "$dist_dir/${name}_${PLATFORM}.zip" ./*
            popd > /dev/null

            rm -rf "$staging"
            echo "→ Created: $dist_dir/${name}_${PLATFORM}.zip"
          done

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: extensions-dist-${{ matrix.platform }}
          path: dist

  prepare-release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo (for version lookups & cdn path)
        uses: actions/checkout@v4

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist

      - name: Generate update_manifest.json for each extension
        shell: bash
        run: |
          #!/usr/bin/env bash
          set -euo pipefail

          for srcdir in dist/extensions-dist-*; do
            [ -d "$srcdir" ] || continue
            echo "→ Moving contents of $srcdir into dist/"
            for file in "$srcdir"/*; do
              mv "$file" dist/
            done
            rm -rf "$srcdir"
          done

          for ext in crates/extensions/*; do
            [ -d "$ext" ] || continue
            name=$(basename "$ext")
            version=$(jq -r .version "$ext/assets/manifest.json")

            manifest="{\"version\":\"$version\",\"assets\":{"
            first=true

            # now glob for dist/{name}_{platform}.zip
            for zip in dist/"${name}"_*.zip; do
              [ -f "$zip" ] || continue
              fname=$(basename "$zip")

              # extract platform from filename
              plat="${fname#${name}_}"
              plat="${plat%.zip}"

              checksum=$(sha256sum "$zip" | cut -d' ' -f1)
              url="${BASE_URL}/${fname}"

              if [ "$first" = true ]; then
                first=false
              else
                manifest+=","
              fi

              manifest+="\"$plat\":{\"url\":\"$url\",\"checksum\":\"$checksum\"}"
            done

            manifest+="}}"

            # emit per-extension JSON
            echo "$manifest" > "dist/${name}-latest.json"
            echo "→ dist/${name}-latest.json"
          done

      - name: Upload release artifacts
        uses: actions/upload-artifact@v4
        with:
          name: release-packages
          path: dist

  publish:
    needs: prepare-release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Download release artifacts
        uses: actions/download-artifact@v4
        with:
          name: release-packages
          path: dist

      - name: Upload assets to latest release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          tag=$(gh api repos/${{ github.repository }}/releases/latest --jq .tag_name)
          echo "Uploading to release $tag…"
          gh release upload "$tag" dist/* --clobber
